FROM python:3.9
WORKDIR /app

# Copying files
RUN mkdir ./app
COPY requirements.txt ./
COPY app/. ./app

# Installing requirements
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

RUN pip install -r ./requirements.txt
ENV FLASK_ENV=production

EXPOSE 5173
CMD ["gunicorn", "-b", ":5173", "app.server:app"]