export const styles = {
    container: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: "25px",
        width: "100%",
        maxWidth: "100vw",
        margin: "0 auto",
        padding: "10px",
        minHeight: "100vh",
        background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
        position: "relative",
        boxSizing: "border-box",
    },
    panel: {
        display: "flex",
        flex: "1",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        width: "100%",
        maxWidth: "600px",
        height: "80vh",
        maxHeight: "750px",
        boxSizing: "border-box",
        padding: "30px",
        background: "rgba(20, 20, 30, 0.8)",
        backdropFilter: "blur(20px)",
        borderRadius: "24px",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
        transition: "all 0.3s ease",
        transform: "translateY(0)",
        ":hover": {
            transform: "translateY(-5px)",
            boxShadow: "0 12px 40px rgba(0, 0, 0, 0.6)",
        },
    },
    panelTitle: {
        fontSize: "28px",
        fontWeight: "600",
        color: "#ffffff",
        marginBottom: "20px",
        textShadow: "0 2px 4px rgba(0, 0, 0, 0.5)",
        letterSpacing: "0.5px",
    },
    videoInputContainer: {
        width: "100%",
        height: "100%",
        borderRadius: "16px",
        overflow: "hidden",
        background: "rgba(10, 10, 20, 0.6)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.05)",
    },
    textarea: {
        width: "100%",
        height: "100%",
        padding: "20px",
        fontSize: "18px",
        resize: "none",
        boxSizing: "border-box",
        background: "rgba(10, 10, 20, 0.7)",
        color: "#ffffff",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        borderRadius: "16px",
        transition: "all 0.3s ease",
        outline: "none",
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        lineHeight: "1.6",
        "::placeholder": {
            color: "rgba(255, 255, 255, 0.4)",
        },
        ":focus": {
            background: "rgba(10, 10, 20, 0.9)",
            borderColor: "rgba(255, 255, 255, 0.2)",
            boxShadow: "0 0 0 3px rgba(255, 255, 255, 0.05)",
        },
    },
    buttons: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: "20px",
        zIndex: 10,
    },
    swapButton: {
        padding: "16px 32px",
        fontSize: "18px",
        fontWeight: "600",
        background: "linear-gradient(135deg,rgb(3, 115, 213) 0%, #00f2fe 100%)",
        color: "#ffffff",
        cursor: "pointer",
        border: "none",
        borderRadius: "50px",
        transition: "all 0.3s ease",
        outline: "none",
        boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
        transform: "translateY(0) scale(1)",
        position: "relative",
        overflow: "hidden",
        ":hover": {
            transform: "translateY(-2px) scale(1.05)",
            boxShadow: "0 0 20px rgba(0, 123, 255, 0.4), 0 0 40px rgba(0, 123, 255, 0.3), 0 0 60px rgba(0, 123, 255, 0.2), 0 6px 20px rgba(0, 0, 0, 0.5)",
            background: "linear-gradient(135deg, #4a5568 0%, #2d3748 100%)",
        },
        ":active": {
            transform: "translateY(0) scale(0.98)",
        },
    },
    translateButton: {
        padding: "16px 32px",
        fontSize: "18px",
        fontWeight: "600",
        background: "linear-gradient(135deg, #a855f7 0%, #3b82f6 100%)",
        color: "#ffffff",
        cursor: "pointer",
        border: "none",
        borderRadius: "50px",
        transition: "all 0.3s ease",
        outline: "none",
        boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
        transform: "translateY(0) scale(1)",
        position: "relative",
        overflow: "hidden",
        ":hover": {
            transform: "translateY(-2px) scale(1.05)",
            boxShadow: "0 0 20px rgba(0, 123, 255, 0.4), 0 0 40px rgba(0, 123, 255, 0.3), 0 0 60px rgba(0, 123, 255, 0.2), 0 6px 20px rgba(0, 0, 0, 0.5)",
            background: "linear-gradient(135deg, #2d3748 0%, #1a202c 100%)",
        },
        ":active": {
            transform: "translateY(0) scale(0.98)",
        },
    },
    buttonContent: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        justifyContent: "center",
    },
    swapIcon: {
        fontSize: "20px",
        transition: "transform 0.3s ease",
    },
    translateIcon: {
        fontSize: "18px",
        transition: "transform 0.3s ease",
    },
    videoContainer: {
        width: "100%",
        height: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderRadius: "16px",
        background: "rgba(10, 10, 20, 0.6)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.05)",
        position: "relative",
    },
    video: {
        width: "100%",
        height: "100%",
        objectFit: "contain",
        borderRadius: "16px",
    },
    videoPlaceholder: {
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        background: "rgba(10, 10, 20, 0.6)",
        backdropFilter: "blur(10px)",
        color: "rgba(255, 255, 255, 0.5)",
        borderRadius: "16px",
        border: "1px solid rgba(255, 255, 255, 0.05)",
        padding: "40px",
        textAlign: "center",
    },
    placeholderIcon: {
        fontSize: "32px",
        marginBottom: "12px",
        opacity: "0.6",
    },
    placeholderText: {
        fontSize: "14px",
        lineHeight: "1.4",
        margin: "0",
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        maxWidth: "280px",
    },
    loadingPlaceholder: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        background: "rgba(10, 10, 20, 0.6)",
        backdropFilter: "blur(10px)",
        borderRadius: "16px",
        border: "1px solid rgba(255, 255, 255, 0.05)",
        padding: "20px",
    },
    spinner: {
        width: "40px",
        height: "40px",
        border: "3px solid rgba(255, 255, 255, 0.1)",
        borderTop: "3px solid rgba(255, 255, 255, 0.6)",
        borderRadius: "50%",
        animation: "spin 1s linear infinite",
        marginBottom: "15px",
    },
    loadingText: {
        fontSize: "14px",
        color: "rgba(255, 255, 255, 0.6)",
        margin: "0",
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        textAlign: "center",
        maxWidth: "280px",
        lineHeight: "1.4",
    },
};
