export const styles = {
    container: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: "25px",
        width: "100%",
        maxWidth: "100vw",
        margin: "0 auto",
        padding: "10px",
        minHeight: "100vh",
        background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
        position: "relative",
        boxSizing: "border-box",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
    },
    panel: {
        width: "100%",
        height: "80vh",
        maxHeight: "750px",
        maxWidth: "600px",
        background: "rgba(255, 255, 255, 0.08)",
        backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        border: "1px solid rgba(255, 255, 255, 0.15)",
        borderRadius: "24px",
        padding: "24px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "center",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.12), 0 0 0 1px rgba(168, 85, 247, 0.25), 0 0 60px rgba(168, 85, 247, 0.18), 0 0 120px rgba(168, 85, 247, 0.12), 0 0 200px rgba(59, 130, 246, 0.08)",
        position: "relative",
        overflow: "hidden",
    },
    panelMobile: {
        height: "auto",
        maxHeight: "none",
        padding: "16px",
        margin: "0",
        minHeight: "300px",
        overflow: "visible",
    },
    panelTitle: {
        fontSize: "28px",
        fontWeight: "600",
        color: "#ffffff",
        marginTop: "0px",
        marginBottom: "20px",
        textShadow: "0 2px 4px rgba(0, 0, 0, 0.5)",
        letterSpacing: "-0.02em",
        textAlign: "center",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
    },
    videoInputContainer: {
        width: "100%",
        height: "100%",
        flex: 1,
        minHeight: 0,
        display: "flex",
        flexDirection: "column",
        borderRadius: "16px",
        background: "rgba(255, 255, 255, 0.05)",
        backdropFilter: "blur(15px)",
        WebkitBackdropFilter: "blur(15px)",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        boxSizing: "border-box",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.05)",
    },
    textarea: {
        flex: 1,
        width: "100%",
        minHeight: 0,
        height: "auto",
        padding: "20px",
        fontSize: "18px",
        resize: "none",
        boxSizing: "border-box",
        background: "rgba(255, 255, 255, 0.05)",
        backdropFilter: "blur(15px)",
        WebkitBackdropFilter: "blur(15px)",
        color: "#ffffff",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        borderRadius: "16px",
        transition: "all 0.3s ease",
        outline: "none",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "400",
        letterSpacing: "-0.01em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        lineHeight: "1.6",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.05)",
        "::placeholder": {
            color: "rgba(255, 255, 255, 0.5)",
            fontFamily: "inherit",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.3)",
        },
        ":focus": {
            background: "rgba(255, 255, 255, 0.08)",
            borderColor: "rgba(255, 255, 255, 0.2)",
            boxShadow: "0 0 0 3px rgba(255, 255, 255, 0.08), 0 6px 20px rgba(0, 0, 0, 0.25), inset 0 1px 0 rgba(255, 255, 255, 0.1)",
        },
    },
    buttons: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: "20px",
        zIndex: 10,
    },
    buttonsMobileTag: {
        flexDirection: "row",
        // order: "-1",
    },
    swapButton: {
        padding: "16px 32px",
        fontSize: "18px",
        fontWeight: "600",
        background: "linear-gradient(135deg,rgb(3, 115, 213) 0%, #00f2fe 100%)",
        color: "#ffffff",
        cursor: "pointer",
        border: "none",
        borderRadius: "50px",
        transition: "all 0.3s ease",
        outline: "none",
        boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
        transform: "translateY(0) scale(1)",
        position: "relative",
        overflow: "hidden",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "500",
        letterSpacing: "-0.005em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        boxSizing: "border-box",
        ":hover": {
            transform: "translateY(-2px) scale(1.05)",
            boxShadow: "0 0 20px rgba(0, 123, 255, 0.4), 0 0 40px rgba(0, 123, 255, 0.3), 0 0 60px rgba(0, 123, 255, 0.2), 0 6px 20px rgba(0, 0, 0, 0.5)",
            background: "linear-gradient(135deg, #4a5568 0%, #2d3748 100%)",
        },
        ":active": {
            transform: "translateY(0) scale(0.98)",
        },
    },
    translateButton: {
        padding: "16px 32px",
        fontSize: "18px",
        fontWeight: "600",
        background: "linear-gradient(135deg, #a855f7 0%, #3b82f6 100%)",
        color: "#ffffff",
        cursor: "pointer",
        border: "none",
        borderRadius: "50px",
        transition: "all 0.3s ease",
        outline: "none",
        boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
        transform: "translateY(0) scale(1)",
        position: "relative",
        overflow: "hidden",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "500",
        letterSpacing: "-0.005em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        boxSizing: "border-box",
        ":hover": {
            transform: "translateY(-2px) scale(1.05)",
            boxShadow: "0 0 20px rgba(0, 123, 255, 0.4), 0 0 40px rgba(0, 123, 255, 0.3), 0 0 60px rgba(0, 123, 255, 0.2), 0 6px 20px rgba(0, 0, 0, 0.5)",
            background: "linear-gradient(135deg, #2d3748 0%, #1a202c 100%)",
        },
        ":active": {
            transform: "translateY(0) scale(0.98)",
        },
    },
    buttonContent: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        justifyContent: "center",
    },
    swapIcon: {
        fontSize: "20px",
        transition: "transform 0.3s ease",
    },
    translateIcon: {
        fontSize: "18px",
        transition: "transform 0.3s ease",
    },
    videoContainer: {
        width: "100%",
        height: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderRadius: "16px",
        background: "black",
        backdropFilter: "blur(10px)",
        WebkitBackdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.05)",
        position: "relative",
        boxSizing: "border-box",
    },
    video: {
        width: "100%",
        height: "100%",
        objectFit: "contain",
        borderRadius: "16px",
    },
    videoPlaceholder: {
        flex: 1,
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        background: "rgba(255, 255, 255, 0.05)",
        backdropFilter: "blur(15px)",
        WebkitBackdropFilter: "blur(15px)",
        color: "rgba(255, 255, 255, 0.7)",
        borderRadius: "16px",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        padding: "40px",
        textAlign: "center",
        boxSizing: "border-box",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.05)",
    },
    placeholderIcon: {
        fontSize: "32px",
        marginBottom: "12px",
        opacity: "0.8",
        filter: "drop-shadow(0 2px 4px rgba(0, 0, 0, 0.3))",
    },
    placeholderText: {
        fontSize: "14px",
        lineHeight: "1.4",
        margin: "0",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "400",
        letterSpacing: "-0.01em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        maxWidth: "280px",
        textShadow: "0 1px 2px rgba(0, 0, 0, 0.4)",
    },
    loadingPlaceholder: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        background: "rgba(255, 255, 255, 0.05)",
        backdropFilter: "blur(15px)",
        WebkitBackdropFilter: "blur(15px)",
        borderRadius: "16px",
        border: "1px solid rgba(255, 255, 255, 0.1)",
        padding: "20px",
        boxSizing: "border-box",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.05)",
    },
    loadingPlaceholderMobile: {
        width: "85%",

    },
    spinner: {
        width: "40px",
        height: "40px",
        border: "3px solid rgba(255, 255, 255, 0.1)",
        borderTop: "3px solid rgba(255, 255, 255, 0.6)",
        borderRadius: "50%",
        animation: "spin 1.33s linear infinite",
        marginBottom: "15px",
    },
    loadingText: {
        fontSize: "14px",
        color: "rgba(255, 255, 255, 0.7)",
        margin: "0",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "400",
        letterSpacing: "-0.01em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        textAlign: "center",
        maxWidth: "280px",
        lineHeight: "1.4",
        textShadow: "0 1px 2px rgba(0, 0, 0, 0.4)",
    },
    clearButton: {
        position: "absolute",
        bottom: "15px",
        right: "15px",
        padding: "12px 18px",
        fontSize: "14px",
        fontWeight: "600",
        background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
        color: "#ffffff",
        border: "none",
        borderRadius: "20px",
        cursor: "pointer",
        transition: "all 0.3s ease",
        boxShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
        fontFamily: "'Inter', 'SF Pro Display', 'Segoe UI Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
        fontWeight: "500",
        letterSpacing: "-0.005em",
        fontFeatureSettings: "'cv02', 'cv03', 'cv04', 'cv11'",
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
        boxSizing: "border-box",
        zIndex: 10,
    },
};
